export interface PeerEnvelopeInput {
  readonly messageId: string;
  readonly conversationId: string;
  readonly parentMessageId?: string;
  readonly senderAgentId: string;
  readonly recipientAgentId: string;
  readonly hopCount: number;
  readonly callChain: readonly string[];
  readonly body: string;
  readonly createdAt: string;
  readonly groupId?: string;
  readonly groupMessageId?: string;
}

export function buildPeerEnvelope(input: PeerEnvelopeInput): string {
  const metadata = {
    protocol: "INTER_AGENT_MESSAGE_V1",
    message_id: input.messageId,
    conversation_id: input.conversationId,
    parent_message_id: input.parentMessageId ?? null,
    from_agent: input.senderAgentId,
    to_agent: input.recipientAgentId,
    hop_count: input.hopCount,
    call_chain: input.callChain,
    created_at: input.createdAt,
    group_id: input.groupId ?? null,
    group_message_id: input.groupMessageId ?? null,
  };
  const encodedBody = JSON.stringify(input.body).replace(
    /[\u2028\u2029\u202a-\u202e\u2066-\u2069]/g,
    (character) => `\\u${character.codePointAt(0)?.toString(16).padStart(4, "0")}`,
  );
  return [
    "INTER_AGENT_MESSAGE_V1",
    "Authenticated routing metadata (generated by the bridge; peer content cannot modify it):",
    JSON.stringify(metadata),
    `BEGIN_UNTRUSTED_PEER_CONTENT_JSON bytes=${Buffer.byteLength(input.body, "utf8")}`,
    encodedBody,
    "END_UNTRUSTED_PEER_CONTENT_JSON",
    "Reply to the peer request. Your authoritative final answer will be returned to the sender.",
  ].join("\n");
}

export function buildAsyncPeerEnvelope(input: PeerEnvelopeInput): string {
  const synchronous = buildPeerEnvelope(input);
  return synchronous
    .replaceAll("INTER_AGENT_MESSAGE_V1", "ASYNC_INTER_AGENT_MESSAGE_V1")
    .replace(
      "Reply to the peer request. Your authoritative final answer will be returned to the sender.",
      "This is asynchronous inbound work. Assistant output is not forwarded automatically. Use reply_to_message explicitly if a network reply is needed.",
    );
}
